### ISSUE TITLE
tutu_data.json报错

### ISSUE THREAD

**Issue by xichu123** [nikissXI/nonebot_plugins#13]
下载插件后没有tutu_data.json文件，自建文件后报错。

**Comment by xichu123** [comment]
03-21 14:26:43 [SUCCESS] nonebot | Running NoneBot...
03-21 14:26:43 [INFO] uvicorn | Started server process [8972]
03-21 14:26:43 [INFO] uvicorn | Waiting for application startup.
03-21 14:26:43 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nb\new-bing\.venv\lib\site-packages\starlette\routing.py", line 675, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\Administrator\Desktop\nb\new-bing\.venv\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\Desktop\nb\new-bing\.venv\lib\site-packages\starlette\routing.py", line 652, in startup
    await handler()
  File "C:\Users\Administrator\Desktop\nb\new-bing\.venv\lib\site-packages\nonebot_plugin_setu_customization\config.py", line 185, in on_startup
    read_data()
  File "C:\Users\Administrator\Desktop\nb\new-bing\.venv\lib\site-packages\nonebot_plugin_setu_customization\config.py", line 138, in read_data
    tmp_data = load(r)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

03-21 14:26:43 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by xichu123** [comment]
{
    "api_list": [
        {
            "name": "dujin",
            "url": "https://api.dujin.org/pic/yuanshen/"
        },
        {
            "name": "mtyqx",
            "url": "https://api.mtyqx.cn/tapi/random.php"
        },
        {
            "name": "dmoe",
            "url": "https://www.dmoe.cc/random.php"
        },
        {
            "name": "ixiaowai",
            "url": "https://api.ixiaowai.cn/api/api.php"
        },
        {
            "name": "yimian",
            "url": "https://api.yimian.xyz/img/"
        },
        {
            "name": "anosu_pixiv",
            "url": "https://image.anosu.top/pixiv/direct"
        },
        {
            "name": "anosu_moe_pixiv",
            "url": "https://moe.anosu.top/img/?sort=pixiv"
        },
        {
            "name": "anosu_moe_setu",
            "url": "https://moe.anosu.top/img/?sort=setu"
        }
    ]
}
json是chatgpt写的

**Comment by xichu123** [comment]
不添加json文件运行，会回复 没有图片api呢

**Comment by xichu123** [comment]
DRIVER=~fastapi
HOST=0.0.0.0  # 配置 NoneBot2 监听的 IP/主机名
PORT=56235  # 配置 NoneBot2 监听的端口
SUPERUSERS=["873078003"]  # 配置 NoneBot 超级用户
command_start=["","/"]
bingchat_command_chat=["bing","蠢古娜"]
bingchat_show_detail = True
petpet_command_start = [""]
petpet_resource_url = https://ghproxy.com/https://raw.githubusercontent.com/noneplugin/nonebot-plugin-petpet/v0.3.x/resources
petpet_disabled_list = []
petpet_gif_max_size = 10
petpet_gif_max_frames = 100
COMMAND_START=[""]

# 必填项
# api超时，这个时间建议设置一分钟以上，否则发图多的时候容易超时报错
api_timeout=60
# 管理员的QQ号（别问我为什么要另外写）
tutu_admin_qqnum = 873078003

# 如果要用P站搜图功能要设置以下内容
# 网页访问地址，就是nonebot的监听地址和端口号，如 http://hahaha.com:80
tutu_site_url = http://127.0.0.1:56235


# 选填项，自己按需求填，不需要的就不要写进配置！
# 选填项，自己按需求填，不需要的就不要写进配置！
# 选填项，自己按需求填，不需要的就不要写进配置！
# 机器人的QQ号列表，如果有多个bot连接，会按照填写的list，左边的机器人QQ优先级最高 1234 > 5678 > 6666，会自动切换
# 如果不填该配置则由第一个连上的bot响应
tutu_bot_qqnum_list = [2196006439]
# 图片下载模式，true则nonebot下载，false则协议端下载
tutu_img_local_download = true
# 图图命令CD时间（秒）
tutu_cooldown = 3
# 一次最多发多少张图
once_send = 5

# R18类别的名称
tutu_r18_name = R18
# 本地图片库的路径
tutu_local_api_path = data/tutu_local_img_lib/
# 本地库二次元文件名称
tutu_self_anime_lib =  self_anime
# 本地库三次元文件名称
tutu_self_cosplay_lib = self_cosplay
# 插件数据文件名
tutu_data_filename = tutu_data.json
# 自定义字体文件路径（要填真实路径，这里只是举个例子）
# tutu_font_path = __file__/font/HYWenHei-85W.ttf
# 字体大小
tutu_font_size = 18
# pixiv图片反代地址，自己可以看看哪个快用哪个 https://i.pixiv.re/ 、 https://i.pixiv.cat/ 、 https://i.loli.best/ 、 https://c.jitsu.top/
tutu_pixiv_proxy = https://i.pixiv.re/
# http代理地址，如 http://127.0.0.1:1234
tutu_http_proxy = http://127.0.0.1:10809
# socks5代理地址，如 socks5://127.0.0.1:1234
tutu_socks5_proxy = socks5://127.0.0.1:10809



# 添加一个接口到二次元类型接口
图图接口管理 二次元 + https://api.dujin.org/pic/yuanshen/
# 支持批量添加接口
图图接口管理 二次元 + 
https://api.mtyqx.cn/tapi/random.php
https://www.dmoe.cc/random.php
https://api.ixiaowai.cn/api/api.php
https://api.yimian.xyz/img/
https://image.anosu.top/pixiv/direct
https://moe.anosu.top/img/?sort=pixiv
https://moe.anosu.top/img/?sort=setu
# 添加一个本地图片库接口到三次元类型接口
图图接口管理 三次元 + 本地图库self_cosplay
# 爬取一篇微信文章的图片到本地图片库self_anime
# https://mp.weixin.qq.com/s/IHeYqZTu8xYLv7nDkRwxUQ self_anime
# 该命令等效于上面的命令 默认2指self_anime，3指self_cosplay
https://mp.weixin.qq.com/s/IHeYqZTu8xYLv7nDkRwxUQ 3







我的env文件配置

**Comment by xichu123** [comment]
浠楚 15:00:16
图图

机器人 15:00:16
没有图片api呢

浠楚 15:01:12
图图接口管理 二次元 https://moe.anosu.top/img/?sort=setu

浠楚 15:01:16
图图

机器人 15:01:17
没有图片api呢

浠楚 15:01:29
图图接口管理 二次元 + https://moe.anosu.top/img/?sort=setu

浠楚 15:01:35
图图

机器人 15:01:35
没有图片api呢

浠楚 15:02:54
图图接口管理 三次元 + 本地图库self_cosplay

浠楚 15:02:58
图图

机器人 15:02:59
没有图片api呢

浠楚 15:03:54
图图接口管理 二次元 + https://api.lolicon.app/setu/v2

浠楚 15:03:58
图图

机器人 15:03:58
没有图片api呢

浠楚 15:04:14
图图接口管理 三次元 + 本地图库self_cosplay

浠楚 15:04:17
图图

机器人 15:04:17
没有图片api呢

浠楚 15:05:48
图图接口管理 二次元 https://api.lolicon.app/setu/v2

浠楚 15:05:52
图图

机器人 15:05:52
没有图片api呢

浠楚 15:10:31
图图接口管理 二次元 + https://api.dujin.org/pic/yuanshen/

浠楚 15:10:33
图图

机器人 15:10:33
没有图片api呢

浠楚 15:11:45
图图接口管理 二次元 + 
https://api.lolicon.app/setu/v2  
http://api.tangdouz.com/sjdmbz.php  
https://api.dujin.org/pic/yuanshen/

浠楚 15:11:48
图图

机器人 15:11:48
没有图片api呢
