### ISSUE TITLE
py插件载入错误

### ISSUE THREAD

**Issue by lintonxue00** [nikissXI/nonebot_plugins#14]
[PyBot][09:51:11.577][ERROR] [plugin]插件导入失败 "nonebot_plugin_setu_customization"
Traceback (most recent call last):
  File "/root/Yunzai-Bot/plugins/py-plugin/main.py", line 15, in <module>
    yunzai_nonebot.load_plugin(plugin.replace("-", "_"))
  File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/root/Yunzai-Bot/plugins/py-plugin/yunzai_nonebot/hijack/plugin.py", line 16, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot_plugin_setu_customization/__init__.py", line 44, in <module>
    from .web import app
  File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot_plugin_setu_customization/web.py", line 18, in <module>
    app = get_asgi()
  File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 121, in get_asgi
    assert isinstance(
AssertionError: asgi object is only available for reverse driver

**Comment by nikissXI** [comment]
不支持云崽
