### ISSUE TITLE
插件报错nonebot_plugin_easy_translate

### ISSUE THREAD

**Issue by QwindF** [nikissXI/nonebot_plugins#33]
使用`pip install nonebot_plugin_easy_translate`进行下载
```python
08-07 18:35:49 [ERROR] nonebot | Failed to import "nonebot_plugin_easy_translate"
Traceback (most recent call last):
  File "D:\BOT\CirnoBot\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "D:\BOT\CirnoBot\cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "D:\BOT\CirnoBot\venv\Lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugin
    return manager.load_plugin(module_path)
> File "D:\BOT\CirnoBot\venv\Lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\BOT\CirnoBot\venv\Lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\BOT\CirnoBot\venv\Lib\site-packages\nonebot_plugin_easy_translate\__init__.py", line 12, in <module>
    from gtranslate.client import Translator
ModuleNotFoundError: No module named 'gtranslate'
```
并且
```python
(venv) PS D:\BOT\CirnoBot> pip.exe install gtranslate                        
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
ERROR: Could not find a version that satisfies the requirement gtranslate (from versions: none)
ERROR: No matching distribution found for gtranslate
```

**Comment by rock8526652** [comment]
在这串加个点
from .gtranslate.client import Translator

**Comment by nikissXI** [comment]
噢，已修复
