### ISSUE TITLE
DLL load failed while importing ujson: 找不到指定的模块。

### ISSUE THREAD

**Issue by Enceladus6** [nikissXI/nonebot_plugins#35]
在云服务器部署时出现错误，windows server 2016， python 3.10.9
```
08-14 14:02:57 [ERROR] nonebot | Failed to import "nonebot_plugin_talk_with_chatgpt"
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot_plugin_talk_with_chatgpt\__init__.py", line 12, in <module>
    from .data_handle import req_chatgpt, text_to_img
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot_plugin_talk_with_chatgpt\data_handle.py", line 3, in <module>
    from ujson import loads
ImportError: DLL load failed while importing ujson: 找不到指定的模块。
```

**Comment by nikissXI** [comment]
呃呃，把里面的ujson改成json

**Comment by nikissXI** [comment]
你系统不支持ujson
